# =============================================================================
# @file    action.yml
# @brief   GitHub Action definition file for the InvenioRDM GitHub Archiver
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file named LICENSE in the repository
# @repo    https://github.com/caltechlibrary/iga
# =============================================================================

name: "IGA"
description: "Automatically archive GitHub releases in an InvenioRDM repository"
author: "Michael Hucka -- https://github.com/mhucka"
branding:
  icon: upload-cloud
  color: orange

inputs:
  INVENIO_SERVER:
    description: "Address of destination InvenioRDM server."
    required: true
  INVENIO_TOKEN:
    description: "Personal Access Token for InvenioRDM server."
    required: true
  all_assets:
    description: "Attach all GitHub assets, not just the source ZIP."
    default: false
    required: false
  all_metadata:
    description: "Include additional metadata from GitHub."
    default: false
    required: false
  community:
    description: "Submit record to the designated RDM community."
    default: false
    required: false
  draft:
    description: "Mark the RDM record as a draft."
    default: false
    required: false
  debug:
    # Note that IGA has more modes than only debug on/off, but for
    # simplicity, this action workflow only offers a binary toggle.
    # Turning on debug also prints additional info in the workflow.
    description: "Print debugging info in the GitHub Action output."
    default: false
    required: false

runs:
  using: composite
  steps:
    - name: Check out a copy of IGA.
      uses: actions/checkout@v3

    - name: Install Python.
      uses: actions/setup-python@v4
      id: setup
      with:
        python-version: "3.11"

    - name: Create a virtualenv to be used as a cache.
      shell: bash
      run: |
        python -m venv ./.venv

    - name: Set up caching.
      uses: actions/cache@v3
      id: cache
      with:
        path: ./.venv/
        key: venv-${{runner.os}}-${{hashFiles('./.venv/pyvenv.cfg')}}
        restore-keys: |
          venv-${{ runner.os }}-

    # - name: Install IGA if it has not been cached yet.
    #   if: steps.cache.outputs.cache-hit != 'true'
    #   shell: bash
    #   run: |
    #     source ./.venv/bin/activate
    #     python -m pip install iga

    - name: echo
      shell: bash
      run: ls -a; ls -a .venv

    - name: Install IGA.
      shell: bash
      # This second pip install will hit the cache for existing things,
      # and will update the cache if iga has been updated.
      run: |
        source ./.venv/bin/activate
        python -m pip install -U iga

    - name: Dump GitHub Actions context and variables if debugging is on.
      if: inputs.debug == true || inputs.debug == 'true'
      env:
        # Setting this variable and then printing it below is not strictly
        # necessary; you could put the expression directly into the echo
        # command below. But when I do that, I get a doubling of the output.
        GITHUB_CONTEXT: ${{toJSON(github)}}
      shell: bash
      run: |
        echo "repository_owner = ${{github.repository_owner}}"
        echo "repository = ${{github.event.repository.name}}"
        echo "release tag = ${{github.ref_name}}"
        echo "====================="
        echo "$GITHUB_CONTEXT"

    - name: Configure IGA options.
      id: vars
      shell: bash
      run: |
        echo "draft=" >> "$GITHUB_ENV"
        echo "all_assets=" >> "$GITHUB_ENV"
        echo "all_metadata=" >> "$GITHUB_ENV"
        echo "use_community=" >> "$GITHUB_ENV"
        echo "community=" >> "$GITHUB_ENV"
        echo "mode=normal" >> "$GITHUB_ENV"
        if [ ! ${{inputs.debug}} == 'false' ]; then
          echo "mode=debug" >> "$GITHUB_ENV"
        fi
        if [ ! ${{inputs.draft}} == 'false' ]; then
          echo "draft='--draft'" >> "$GITHUB_ENV"
        fi
        if [ ! ${{inputs.all_assets}} == 'false' ]; then
          echo "all_assets='--all-assets'" >> "$GITHUB_ENV"
        fi
        if [ ! ${{inputs.all_metadata}} == 'false' ]; then
          echo "all_metadata='--all-metadata'" >> "$GITHUB_ENV"
        fi
        if [ ! ${{inputs.community}} == 'false' ]; then
          echo "use_community='--community'" >> "$GITHUB_ENV"
          echo "community='${{inputs.community}}'" >> "$GITHUB_ENV"
        fi

    - name: Run IGA.
      shell: bash
      env:
        INVENIO_SERVER: ${{inputs.INVENIO_SERVER}}
        INVENIO_TOKEN: ${{inputs.INVENIO_TOKEN}}
        GITHUB_TOKEN: ${{github.token}}
      run: |
        source ./.venv/bin/activate
        echo "record_url=$(iga --log-dest iga.out --mode ${{env.mode}} --github-account ${{github.repository_owner}} --github-repo ${{github.event.repository.name}} ${{env.draft}} ${{env.all_assets}} ${{env.all_metadata}} ${{env.use_community}} ${{env.community}} ${{github.ref_name}})" >> $GITHUB_ENV

    - name: Summarize the results.
      shell: bash
      run: |
        echo \#\# Successfully archived release ${{github.ref_name}} >> $GITHUB_STEP_SUMMARY
        echo URL of the new InvenioRDM record: ${{env.record_url}}   >> $GITHUB_STEP_SUMMARY
