# =============================================================================
# GitHub Action workflow for using the InvenioRDM GitHub Archiver (IGA).
# A copy of this file is available from https://github.com/caltechlibrary/iga/.
# At the time this file was copied, IGA was at version 0.0.15.
# =============================================================================

name: InvenioRDM GitHub Archiver

env:
  # 👋🏻 Set the next variable to your InvenioRDM server address 👋🏻
  INVENIO_SERVER: https://your-invenio-server.org

  # These variables are IGA options. Please see the docs for info.
  draft:         false
  all_assets:    false
  all_metadata:  false
  community:     none
  parent_record: none
  debug:         false

# ~~~~~~~~~~~~~~~~ The rest of this file should be left as-is. ~~~~~~~~~~~~~~~~

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: "The tag of the release to archive:"
      draft:
        default: false
        description: "Mark the record as a draft:"
      all_assets:
        default: false
        description: "Attach all GitHub assets:"
      all_metadata:
        default: false
        description: "Include additional GitHub metadata:"
      community:
        description: "Send record to InvenioRDM community:"
      parent_record:
        description: "ID of parent record (for versioning):"

jobs:
  Send_to_InvenioRDM:
    runs-on: ubuntu-latest
    steps:
      - uses: caltechlibrary/iga@main
        with:
          INVENIO_SERVER: ${{env.INVENIO_SERVER}}
          INVENIO_TOKEN:  ${{secrets.INVENIO_TOKEN}}
          all_assets:     ${{github.event.inputs.all_assets || env.all_assets}}
          all_metadata:   ${{github.event.inputs.all_metadata || env.all_metadata}}
          debug:          ${{github.event.inputs.debug || 'false'}}
          draft:          ${{github.event.inputs.draft || env.draft}}
          community:      ${{github.event.inputs.community || env.community}}
          parent_record:  ${{github.event.inputs.parent_record || env.parent_record}}
          release_tag:    ${{github.event.inputs.release_tag || 'latest'}}
