#!/usr/bin/env python3

from   commonpy.data_structures import CaseFoldSet
import gzip
from   os import path
import pickle
import sys

parent = path.dirname(path.abspath(__file__))
sys.path.append(path.dirname(parent))
sys.path.append(path.dirname(path.dirname(parent)))

from iga.name_utils import _cleaned_name


def orgs_from_file():
    orgs = CaseFoldSet()
    with open('org-names.txt', 'r') as f:
        for line in f.readlines():
            orgs.add(_cleaned_name(line))
    return orgs


orgs = orgs_from_file()
with open('org-names.p', 'wb') as f:
    pickle.dump(orgs, f)

print(f'Wrote {len(orgs)} org names to pickle file')
