#!/bin/bash
# ================================================================== -*- sh -*-
# @file    download-sample-repo
# @brief   Download limited subset of a GitHub repo to use for testing
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file LICENSE in the repository containing this file.
# @repo    https://github.com/caltechlibrary/iga
#
# This is a pretty simple script that downloads JSON data from the GitHub API,
# plus some additional files like codemeta.json and CITATION.cff, for a given
# release of a software project. It saves the results in the current directory
# in a subdirectory named after "account/repo". I use this to save the various
# repo snapshots in tests/data/github-examples/.
#
# This assumes a GitHub "classic" PAT is contained in the environment
# variable GITHUB_TOKEN.
# =============================================================================

account=$1
repo=$2
tag=$3

if (( $# < 2 )); then
    echo "Usage: get-github ACCOUNT REPO TAG"
    exit 1
fi

if [[ -z "${GITHUB_TOKEN}" ]]; then
    echo "GITHUB_TOKEN variable not set"
    exit 1
fi

mkdir -p $account/$repo

echo "Created $account/$repo"
echo "Downloading files for $account/$repo ..."

API=https://api.github.com

header="Authorization: token $GITHUB_TOKEN"
curl -H "$header" -s $API/repos/$account/$repo > $account/$repo/repo.json
curl -H "$header" -s $API/repos/$account/$repo/releases/tags/$tag > $account/$repo/release.json
curl -H "$header" -s $API/users/$account > $account/$repo/account.json

branch=$(jq -r .default_branch $account/$repo/repo.json)
treesurl="$API/repos/$account/$repo/git/trees/$branch"

echo '[' > $account/$repo/filenames.json
curl -H "$header" -s $treesurl | jq '.tree[].path' | sed 's/$/,/g' >> $account/$repo/filenames.json
echo ']' >> $account/$repo/filenames.json

license=$(egrep -i licen.e $account/$repo/filenames.json | tr -d ',"')

for file in codemeta.json CITATION.cff citation.cff $license; do
    curl -H "$header" -s $API/repos/$account/$repo/contents/$file > $account/$repo/tmp
    if ! grep -q "Not Found" $account/$repo/tmp; then
       jq -r .content < $account/$repo/tmp | base64 -D > $account/$repo/$file
    fi
    rm -f $account/$repo/tmp
done

echo "Downloading files for $account/$repo ... Done."
echo "Cleaning up..."

# Delete empty files.

find $account/$repo -type f -size -4c | xargs rm
grep -rl '"message": "Not Found"' $account/$repo | xargs rm

echo "Cleaning up... Done."
