name: Lint Markdown files
on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v13
      with:
        config: '.markdownlint.json'
        globs: |
          README.md
          CHANGES.md
