# @file    markdown-linter.yml
# @brief   GitHub Actions workflow to run a Markdown linter on .md files
# @author  Michael Hucka <mhucka@caltech.edu>
# @license Please see the file named LICENSE in the repository
# @repo    https://github.com/caltechlibrary/iga

name: Lint Markdown files
run-name: Lint Markdown files after ${{github.event_name}} by ${{github.actor}}

on:
  push:
    paths:
      - '*.md'
  pull_request:
    paths:
      - '*.md'
  workflow_dispatch:
    paths:
      - '*.md'

jobs:
  lint:
    name: "Run Markdown linter"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v13
      with:
        config: '.markdownlint.json'
        globs: |
          *.md
